site_name: Firestarter Docs
theme:
  name: material
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github 
  favicon: assets/favicon.png
  palette:
    primary: white
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.sections
nav:
  - Welcome to Firestarer: 
      - index.md
      - technologies.md
  - Setup:
      - setup/index.md
      - setup/source-code.md
      - setup/local-development.md
      - setup/firebase-account.md
      - setup/firebase-config.md
      - setup/vercel-account.md
      - setup/github-actions.md
      - setup/congratulations.md
  - Understanding the code:
      - code/index.md
  - Tutorials:
      - tutorials/index.md
repo_url: https://github.com/mcapodici/firestarter
repo_name: mcapodici/firestarter
markdown_extensions:
  - attr_list 
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg